import { Entypo } from '@expo/vector-icons';
import { MaterialIcons } from '@expo/vector-icons';
export  const data = [
    {
      name: 'Vegetable soup ',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic1.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },
   {
      name: 'Fried Chicken',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic2.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },
   {
      name: 'Spaghetti',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic3.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },
   {
      name: 'Milk Shade 200cl',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic4.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },
   {
      name: 'Spaghetti ',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic5.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },
   {
      name: 'Egusi Soup ',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic6.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },
   {
      name: 'Fried Goat meat',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic7.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },
   {
      name: 'Orange Juice 200cl',
      Price: 'NGN 3,000',
      icon: <Entypo name="shopping-cart" size={24} color="black" />,
      icon2: <MaterialIcons name="favorite" size={24} color="black" />,
      image: require('../assets/images/pic8.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
   },

]

export const Fooddetails = [
   
   {
      id: 2,
      name: 'Vegetable soup ',
      Price: 'NGN 3,000',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
      image: require('../assets/images/pic2.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
   },
   {
      id: 3,
      name: 'Vegetable soup + semo',
      Price: 'NGN 3,000',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
      image: require('../assets/images/pic3.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
   },
   {
      id: 4,
      name: 'Vegetable soup + semo',
      Price: 'NGN 3,000',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
      image: require('../assets/images/pic4.png'),
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
   },
   {
      id: 5,
      name: 'Vegetable soup + semo',
      Price: 'NGN 3,000',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
      image: require('../assets/images/pic5.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
   },
   {
      id: 6,
      name: 'Vegetable soup + semo',
      Price: 'NGN 3,000',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
      image: require('../assets/images/pic6.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
   },
   {
      id: 7,
      name: 'Vegetable soup + semo',
      Price: 'NGN 3,000',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
      image: require('../assets/images/pic7.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
   },
   {
      id: 8,
      name: 'Vegetable soup + semo',
      Price: 'NGN 3,000',
      title: 'Vegetable soup with Semo/Garri is a Nigeria delicacy made from vegetable leaves, Nutritious and appetizing',
      image: require('../assets/images/pic8.png'),
      wrap: 'Wrap',
      extra1: 'Fried Chicken',
      extra2: 'Fried goat Meat',
      extra3: 'Fried fish',
      extra4: 'Garri',
      extra5: 'Fufu',
      extra6: 'Semo',
   },
]